### ISSUE TITLE
Last item of the first line is not aligned

### ISSUE THREAD

**Issue by Aure77** [hadalin/jquery-flickr-photoset#1]
Hi, I try your script with another bootstrap theme (http://bootswatch.com/cyborg/), but I get the following behaviour :
![Image of flickr-photoset](https://i.imgur.com/DqDWbZH.jpg)
The last photo on the first line (and only the first line) is displaced compared to others photos.
Can you help me ?

**Comment by hadalin** [comment]
Sorry no, I don't do support in cases where the script is used in some custom way.

**Comment by Aure77** [comment]
too bad... I think the problem is becauce I am using bootstrap v3.2.0 and your script has been developped with 3.1.1

**Comment by hadalin** [comment]
Or maybe because you're using different theme which has different CSS rules.

**Comment by Aure77** [comment]
I found the problem. It's my fault. I forgot a `&nbsp;` into "gallery-container" that cause this behaviour. sorry.
