### ISSUE TITLE
Flickr galery works in local only.

### ISSUE THREAD

**Issue by aredqueen22** [hadalin/jquery-flickr-photoset#2]
I didn't see my galery with your codes even if my galery in flickr is active and public. why?

**Comment by hadalin** [comment]
This is like calling your doctor, telling him you have a headache and expecting him to give you a diagnosis.

**Comment by aredqueen22** [comment]
<div class="gallery" id="photo">
            <div class="row">
                <div class="col-xs-12 spinner-wrapper">
                    <div class="spinner"></div>
                </div>
                <div class="gallery-container"></div>
            </div>
        </div>

        
        <div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
            <div class="slides"></div>
            <h3 class="title"></h3>
            <a class="prev">‹</a>
            <a class="next">›</a>
            <a class="close">×</a>
            <a class="play-pause"></a>
            <ol class="indicator"></ol>
            <div class="modal fade">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" aria-hidden="true">&times;</button>
                            <h4 class="modal-title"></h4>
                        </div>
                        <div class="modal-body next"></div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default pull-left prev">
                                <i class="glyphicon glyphicon-chevron-left"></i>
                                Previous
                            </button>
                            <button type="button" class="btn btn-primary next">
                                Next
                                <i class="glyphicon glyphicon-chevron-right"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div> 

...

<script type="text/javascript">
        $(function() {
            
            // Set blueimp gallery options.
            $.extend(blueimp.Gallery.prototype.options, {
                useBootstrapModal: false,
                hidePageScrollbars: false
            });

            // Engage gallery.
            $('.gallery').flickr({
                apiKey: '774ba7e1b9df7d6310195c0d99007f72',
                photosetId: '72157658566003666'
            });
        });
        </script>

I put this in my page and I link your jquery library and css but I see my flickr galery in local but not online. This is normal?

**Comment by aredqueen22** [comment]
Sorry, I will explain clearly. I put your codes, css and jquery library.. and my apikey and my photoset id in the script. But i didn't see my flickr gallery online on my website just in local on my computer...

**Comment by aredqueen22** [comment]
http://www.audreylehoux.com/lucie_dominic/index.html

**Comment by aredqueen22** [comment]
Because after the picture of the bride family , we must to see the flickr gallery.. but nothing.

**Comment by aredqueen22** [comment]
And my gallery on flickr is public and active.

**Comment by hadalin** [comment]
Sorry, but open source does not mean free support. I won't debug your code.

Cheers.
